### ISSUE TITLE
Communicate android from hosted Vue base website

### ISSUE THREAD

**Issue by waseem786** [sreeharikv112/WebViewNativeComm#1]
Hi, 
First of all I thanking you for the clear documentation and the sample project.
Here I need to implement another feature.
Lets say, I have a hosted site with a button like you design in side android. When I press the button on hosted site, I want to get a click message in android. Is there any way to do this?

**Comment by sreeharikv112** [comment]
@waseem786  
I have not specifically tried this out with Vue.js . But logic remains the same. Go through this portal and let me know if this work. https://www.programmersought.com/article/8455235099/



`webView.addJavascriptInterface(this, "androidinfo");//Add js listener so html can call the client
`
```
methods:{
		  scanclick(){
		     Var str = window.androidinfo.showInfoFromJs("from JS");
	  		this.$toast(str);
	  			},
}
```

And in the JS bridge the following will be used

```
@JavascriptInterface
    public  String showInfoFromJs(String str){
                 android.util.Log.i("tag", "From JS: "+str); 
                 String s = "returned parameter";     
        return s;
    }
```
